# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81ce51a6cc7224713ee2a93d04ff40310918b1f55660aba03f2e4effcb2b4d09965f824e5f4efe86f64392418056d6bd093de1c61c01a63aee4e6799543de4e1

test:
  secret_key_base: dd5330cabc02e8431e02b644e57d9ef40be510278be458c45987c994ae2d18e6d522f98c8209fca76df6dac582405223a55a3ad6389d1ea4e4509a2e7afa1b78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
